//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestBotThing {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class userSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static userSettings defaultInstance = ((userSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new userSettings())));
        
        public static userSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[channel] is no longer taking requests. BibleThump")]
        public string requestPause {
            get {
                return ((string)(this["requestPause"]));
            }
            set {
                this["requestPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[channel] is now taking requests! PogChamp")]
        public string requestUnpause {
            get {
                return ((string)(this["requestUnpause"]));
            }
            set {
                this["requestUnpause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!request")]
        public string requestCommand {
            get {
                return ((string)(this["requestCommand"]));
            }
            set {
                this["requestCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[user] has changed their request. (#[requestNumber] in line)")]
        public string requestChanged {
            get {
                return ((string)(this["requestChanged"]));
            }
            set {
                this["requestChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[user] has requested a song. (#[requestNumber] in line)")]
        public string requestAdded {
            get {
                return ((string)(this["requestAdded"]));
            }
            set {
                this["requestAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[user]: [channel] is not taking requests. BibleThump")]
        public string requestDisabled {
            get {
                return ((string)(this["requestDisabled"]));
            }
            set {
                this["requestDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Requests are live! PogChamp")]
        public string requestConnected {
            get {
                return ((string)(this["requestConnected"]));
            }
            set {
                this["requestConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Request by [user] was removed.")]
        public string requestRemoved {
            get {
                return ((string)(this["requestRemoved"]));
            }
            set {
                this["requestRemoved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!remove")]
        public string removeCommand {
            get {
                return ((string)(this["removeCommand"]));
            }
            set {
                this["removeCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thanks [user] for following! PogChamp")]
        public string newFollow {
            get {
                return ((string)(this["newFollow"]));
            }
            set {
                this["newFollow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thanks [user] for the sub! PogChamp")]
        public string newSub {
            get {
                return ((string)(this["newSub"]));
            }
            set {
                this["newSub"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[user] has resubbed for [amount] months! PogChamp")]
        public string newResub {
            get {
                return ((string)(this["newResub"]));
            }
            set {
                this["newResub"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[user] is now hosting with [amount] viewers! PogChamp")]
        public string newHost {
            get {
                return ((string)(this["newHost"]));
            }
            set {
                this["newHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[user] is raiding with [amount] raiders! PogChamp")]
        public string newRaid {
            get {
                return ((string)(this["newRaid"]));
            }
            set {
                this["newRaid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[user] just donated [amount]! PogChamp")]
        public string newDonation {
            get {
                return ((string)(this["newDonation"]));
            }
            set {
                this["newDonation"] = value;
            }
        }
    }
}
